#include "menu.h"
#include "singletons.h"
#include <string>
#include <iostream>

using namespace std; //TODO: remove

Menu::Menu() {
  ui_xml =
  "<interface>"
  "  <menu id='juci-menu'>"
  "    <section>"
  "      <item>"
  "        <attribute name='label' translatable='yes'>_About</attribute>"
  "        <attribute name='action'>app.about</attribute>"
  "      </item>"
  "    </section>"
  "    <section>"
  "      <item>"
  "        <attribute name='label' translatable='yes'>_Preferences</attribute>"
  "        <attribute name='action'>app.preferences</attribute>"
  "      </item>"  
  "    </section>"
  "    <section>"
  "      <item>"
  "        <attribute name='label' translatable='yes'>_Quit</attribute>"
  "        <attribute name='action'>app.quit</attribute>"
  "      </item>"  
  "    </section>"
  "  </menu>"
  ""
  "  <menu id='window-menu'>"
  "    <submenu>"
  "      <attribute name='label' translatable='yes'>_File</attribute>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_New _File</attribute>"
  "          <attribute name='action'>app.new_file</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_New _Directory</attribute>"
  "          <attribute name='action'>app.new_folder</attribute>"
  "        </item>"
  "        <submenu>"
  "          <attribute name='label' translatable='yes'>_New _Project</attribute>"
  "          <item>"
  "            <attribute name='label' translatable='no'>C++</attribute>"
  "            <attribute name='action'>app.new_project_cpp</attribute>"
  "          </item>"
  "        </submenu>"
  "      </section>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Open _File</attribute>"
  "          <attribute name='action'>app.open_file</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Open _Folder</attribute>"
  "          <attribute name='action'>app.open_folder</attribute>"
  "        </item>"
  "      </section>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Save</attribute>"
  "          <attribute name='action'>app.save</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Save _As</attribute>"
  "          <attribute name='action'>app.save_as</attribute>"
  "        </item>"
  "      </section>"
  "    </submenu>"
  ""
  "    <submenu>"
  "      <attribute name='label' translatable='yes'>_Edit</attribute>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Undo</attribute>"
  "          <attribute name='action'>app.edit_undo</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Redo</attribute>"
  "          <attribute name='action'>app.edit_redo</attribute>"
  "        </item>"
  "      </section>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Cut</attribute>"
  "          <attribute name='action'>app.edit_cut</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Copy</attribute>"
  "          <attribute name='action'>app.edit_copy</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Paste</attribute>"
  "          <attribute name='action'>app.edit_paste</attribute>"
  "        </item>"
  "      </section>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Find</attribute>"
  "          <attribute name='action'>app.edit_find</attribute>"
  "        </item>"
  "      </section>"
  "    </submenu>"
  ""
  "    <submenu>"
  "      <attribute name='label' translatable='yes'>_Source</attribute>"
  "      <section>"
  "        <submenu>"
  "          <attribute name='label' translatable='yes'>_Spell _Check</attribute>"
  "          <item>"
  "            <attribute name='label' translatable='yes'>_Spell _Check _Buffer</attribute>"
  "            <attribute name='action'>app.source_spellcheck</attribute>"
  "          </item>"
  "          <item>"
  "            <attribute name='label' translatable='yes'>_Clear _Spelling _Errors</attribute>"
  "            <attribute name='action'>app.source_spellcheck_clear</attribute>"
  "          </item>"
  "          <item>"
  "            <attribute name='label' translatable='yes'>_Go _to _Next _Spelling _Error</attribute>"
  "            <attribute name='action'>app.source_spellcheck_next_error</attribute>"
  "          </item>"
  "        </submenu>"
  "      </section>"
  "      <section>"
  "        <submenu>"
  "          <attribute name='label' translatable='yes'>_Indentation</attribute>"
  "          <item>"
  "            <attribute name='label' translatable='yes'>_Set _Current _Buffer _Tab</attribute>"
  "            <attribute name='action'>app.source_indentation_set_buffer_tab</attribute>"
  "          </item>"
  "          <item>"
  "            <attribute name='label' translatable='yes'>_Auto-Indent _Current _Buffer</attribute>"
  "            <attribute name='action'>app.source_indentation_auto_indent_buffer</attribute>"
  "          </item>"
  "        </submenu>"
  "      </section>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Go _to _Line</attribute>"
  "          <attribute name='action'>app.source_goto_line</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Center _Cursor</attribute>"
  "          <attribute name='action'>app.source_center_cursor</attribute>"
  "        </item>"
  "      </section>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Find _Documentation</attribute>"
  "          <attribute name='action'>app.source_find_documentation</attribute>"
  "        </item>"
  "      </section>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Go to Declaration</attribute>"
  "          <attribute name='action'>app.source_goto_declaration</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Go to Method</attribute>"
  "          <attribute name='action'>app.source_goto_method</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Rename</attribute>"
  "          <attribute name='action'>app.source_rename</attribute>"
  "        </item>"
  "      </section>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Go to Next Diagnostic</attribute>"
  "          <attribute name='action'>app.source_goto_next_diagnostic</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Apply Fix-Its</attribute>"
  "          <attribute name='action'>app.source_apply_fix_its</attribute>"
  "        </item>"
  "      </section>"
  "    </submenu>"
  ""
  "    <submenu>"
  "      <attribute name='label' translatable='yes'>_Project</attribute>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Compile _and _Run</attribute>"
  "          <attribute name='action'>app.compile_and_run</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Compile</attribute>"
  "          <attribute name='action'>app.compile</attribute>"
  "        </item>"
  "      </section>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Run _Command</attribute>"
  "          <attribute name='action'>app.run_command</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Kill _Last _Process</attribute>"
  "          <attribute name='action'>app.kill_last_running</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Force _Kill _Last _Process</attribute>"
  "          <attribute name='action'>app.force_kill_last_running</attribute>"
  "        </item>"
  "      </section>"
  "    </submenu>"
  ""
  "    <submenu>"
  "      <attribute name='label' translatable='yes'>_Window</attribute>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Next _Tab</attribute>"
  "          <attribute name='action'>app.next_tab</attribute>"
  "        </item>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Previous _Tab</attribute>"
  "          <attribute name='action'>app.previous_tab</attribute>"
  "        </item>"
  "      </section>"
  "      <section>"
  "        <item>"
  "          <attribute name='label' translatable='yes'>_Close _Tab</attribute>"
  "          <attribute name='action'>app.close_tab</attribute>"
  "        </item>"
  "      </section>"
  "    </submenu>"
  "  </menu>"
  "</interface>";
}

void Menu::add_action(const std::string &name, std::function<void()> action) {
  auto application = builder->get_application();
  
  actions[name]=application->add_action(name, action);
}

void Menu::set_keys() {
  auto application = builder->get_application();
  
  for(auto &key: Singleton::Config::menu()->keys) {
    if(key.second.size()>0 && actions.find(key.first)!=actions.end())
      application->set_accel_for_action("app."+key.first, key.second);
  }
}

void Menu::build() {
  builder = Gtk::Builder::create();
  
  try {
    builder->add_from_string(ui_xml);
  }
  catch (const Glib::Error &ex) {
    std::cerr << "building menu failed: " << ex.what();
  }
}
